[[items]]
template = "emacs"
file = "~/.emacs.d/base16-custom-theme.el"
rewrite = true

[[items]]
template = "kde-plasma"
file = "~/.local/share/color-schemes/Base16Custom.colors"
rewrite = true
hook = "plasma-apply-colorscheme BreezeLight; plasma-apply-colorscheme Base16Custom"

[[items]]
template = "konsole"
subtemplate = "complement"
file = "~/.local/share/konsole/Base16Custom.colorscheme"
rewrite = true

[[items]]
template = "shell"
subtemplate = "complement"
file = "~/.config/base16-shell/scripts/base16-custom.sh"
rewrite = true

