[[items]]
file = "~/.emacs.d/base16-custom-theme.el"
template = "emacs"
rewrite = true

[[items]]
file = "~/.config/base16-shell/scripts/base16-custom.sh"
template = "shell"
subtemplate = "complement"
rewrite = true

[[items]]
file = "~/.local/share/konsole/Base16Custom.colorscheme"
template = "konsole"
subtemplate = "complement"
rewrite = true
